events {}

http {
    include /etc/nginx/mime.types;

    upstream backend {
        server backend:3000;
    }

    server {
        listen 80;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://backend/;
        }
    }
}
